account_id = "2bd99d5b13b2186382cd3dc995b0bb18"
name = "booklog-ai"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com/chat/completions"

[[kv_namespaces]]
binding = "BOOKLOG_KV"
id = "2eca5cd458434e5a88686a13482eab7d"
