account_id = "049ff5e84ecf636b53b162cbb580aae6"
name = "booklog-ai"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com/chat/completions"

[[kv_namespaces]]
binding = "BOOKLOG_KV"
id = "ce618dc102f9427cb4e896ff3aad851e"
